modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Automatic%20Doors"
logoFile="icon.png"

[[mods]]
modId="automaticdoors"
version="4.4"
displayName="Automatic Doors"
displayURL="https://curseforge.com/minecraft/mc-mods/automatic-doors"
authors="Rick South"
description='''Automatically opens doors in front of the player and closes them with a configurable delay.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.automaticdoors]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"